#
# This workflow calls the main distribution pipeline from DuckDB to build, test and (optionally) release the extension
#
name: Main Extension Distribution Pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

jobs:
  duckdb-v1-4-0-build:
    name: Build extension binaries (DuckDB v1.4.0)
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@v1.4-andium
    with:
      duckdb_version: v1.4.0
      ci_tools_version: v1.4-andium
      extension_name: dplyr
      extra_toolchains: rust

  duckdb-v1-4-5-build:
    name: Build extension binaries (DuckDB v1.4.5)
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@v1.4-andium
    with:
      duckdb_version: v1.4.5
      ci_tools_version: v1.4-andium
      extension_name: dplyr
      extra_toolchains: rust
